#:schema node_modules/wrangler/config-schema.json
name = "akasublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "ca06d05cd3f9426f88cb53f1149589dc" }
]

[assets]
directory = "./public"
